server:
   port: 8888

spring:
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               searchLocations: /home/german/Documentos/MS-Proyect/ms-cloud-config